---
title: "zambiags"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{zambiags}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(zambiags)
library(geospaar)
```


```{r}
ss01 <- raster("data/season_planting_date_30perc/season_01.tif")
ss02 <- raster("data/season_planting_date_30perc/season_02.tif")
ss03 <- raster("data/season_planting_date_30perc/season_03.tif")
ss04 <- raster("data/season_planting_date_30perc/season_04.tif")
ss05 <- raster("data/season_planting_date_30perc/season_05.tif")
ss06 <- raster("data/season_planting_date_30perc/season_06.tif")
ss07 <- raster("data/season_planting_date_30perc/season_07.tif")
ss08 <- raster("data/season_planting_date_30perc/season_08.tif")
ss09 <- raster("data/season_planting_date_30perc/season_09.tif")
ss10 <- raster("data/season_planting_date_30perc/season_10.tif")
ss11 <- raster("data/season_planting_date_30perc/season_11.tif")
ss12 <- raster("data/season_planting_date_30perc/season_12.tif")
ss13 <- raster("data/season_planting_date_30perc/season_13.tif")
ss14 <- raster("data/season_planting_date_30perc/season_14.tif")
ss15 <- raster("data/season_planting_date_30perc/season_15.tif")
ss16 <- raster("data/season_planting_date_30perc/season_16.tif")
ss17 <- raster("data/season_planting_date_30perc/season_17.tif")
ss18 <- raster("data/season_planting_date_30perc/season_18.tif")

#create season start stack
l <- list(ss01, ss02, ss03, ss04, ss05, ss06, ss07, ss08, ss09, ss10, ss11, ss12, ss13, ss14, ss15, ss16, ss17, ss18)

season_start_stack <- stack(l)

plot_noaxes(season_start_stack)
```

```{r}
#Season End Tif
se01 <- raster("data/season_end_30perc/season_01.tif")
se02 <- raster("data/season_end_30perc/season_02.tif")
se03 <- raster("data/season_end_30perc/season_03.tif")
se04 <- raster("data/season_end_30perc/season_04.tif")
se05 <- raster("data/season_end_30perc/season_05.tif")
se06 <- raster("data/season_end_30perc/season_06.tif")
se07 <- raster("data/season_end_30perc/season_07.tif")
se08 <- raster("data/season_end_30perc/season_08.tif")
se09 <- raster("data/season_end_30perc/season_09.tif")
se10 <- raster("data/season_end_30perc/season_10.tif")
se11 <- raster("data/season_end_30perc/season_11.tif")
se12 <- raster("data/season_end_30perc/season_12.tif")
se13 <- raster("data/season_end_30perc/season_13.tif")
se14 <- raster("data/season_end_30perc/season_14.tif")
se15 <- raster("data/season_end_30perc/season_15.tif")
se16 <- raster("data/season_end_30perc/season_16.tif")
se17 <- raster("data/season_end_30perc/season_17.tif")
se18 <- raster("data/season_end_30perc/season_18.tif")

#create season end stack
l2 <- list(se01, se02, se03, se04, se05, se06, se07, se08, se09, se10, se11, se12, se13, se14, se15, se16, se17, se18)

season_end_stack <- stack(l2)

plot_noaxes(season_end_stack)
```


